# Generated by Django 5.2.17 on 2026-09-02 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('collecting', 'Collecting'), ('revealed', 'Revealed'), ('clustering', 'Clustering'), ('voting', 'Voting'), ('discussing', 'Discussing'), ('closed', 'Closed')], default='collecting', max_length=20)),
                ('opens_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('voting_closed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='projects.project')),
            ],
            options={
                'ordering': ['-opens_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'closed'), _negated=True), fields=('project',), name='unique_active_cycle_per_project')],
            },
        ),
    ]
