# Generated by Django 5.2.17 on 2026-09-02 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_feedbackcycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(choices=[('suggested', 'Suggested'), ('human', 'Human')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='projects.feedbackcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('continue', 'Continue')], max_length=20)),
                ('text', models.CharField(max_length=280)),
                ('edit_token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='projects.feedbackcycle')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='projects.cluster')),
            ],
        ),
    ]
