# Generated by Django 5.2.17 on 2026-09-07 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_cycleparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.cluster')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.feedbackcycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cycle', 'member', 'cluster'), name='unique_vote_per_member_cluster'), models.CheckConstraint(condition=models.Q(('weight__gte', 1)), name='vote_weight_at_least_one')],
            },
        ),
    ]
