# Generated by Django 5.2.17 on 2026-09-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('outcome', models.CharField(blank=True, choices=[('discussed', 'Discussed'), ('skipped', 'Skipped'), ('deferred', 'Deferred')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topic', to='projects.cluster')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
