# Generated by Django 5.2.17 on 2026-09-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_discussiontopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('transcript_file', 'Transcript file'), ('pasted_text', 'Pasted text')], max_length=20)),
                ('transcript_text', models.TextField(blank=True)),
                ('processing_state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_records', to='projects.feedbackcycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
