# Generated by Django 5.2.17 on 2026-09-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_meetingrecord_extracted_summary_actionitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrospectiveSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='projects.feedbackcycle')),
            ],
        ),
    ]
